### PR TITLE
Feature/added regex example

### PR DESCRIPTION
**Pull request by mariomurrent-softwaresolutions**
Can you please check the added example. Seems like the regex is not working.

`const requestAnswer = curr.requests.find(r => isEqual(r.input, call.request));`

regexMatch will always be false. Did I break something on the last merge, or what was the intended behaviour?
Where did we say we want to add the regexmatch property?

### CODE REVIEW

**Comment by mariomurrent-softwaresolutions** [comment]
I guess, regex match for properties of an object is not supported right?

**Comment by dushanpantic** [comment]
You didnt break anything with the last merge.
The idea I had was to have `--matched` work with absolute values, and then later add `--matched-regex` to work with regex values. I just didnt have time to do it. I'll try to implement it tonight

**Review by dushanpantic — APPROVED** [review]

**Comment by mariomurrent-softwaresolutions** [comment]
> You didnt break anything with the last merge.
> 
> The idea I had was to have `--matched` work with absolute values, and then later add `--matched-regex` to work with regex values. I just didnt have time to do it. I'll try to implement it tonight

Ah that's true.
Please don't stress yourself 😊

**Comment by dushanpantic** [comment]
I liked the way you suggested in this PR over the `--matched-regex` flag, so I implemented it.
Go to the [regex autowire example](./examples/autowire-regex) and run `grpc-server-mock start:autowire --matched`. 
It should work.
Also, take a look at the example change I merged here: https://github.com/dushanpantic/grpc-server-mock/commit/53dd2dcf87df725848b3fe39988c658fd1d7aa3c

**Comment by mariomurrent-softwaresolutions** [comment]
Thank you the fast implementation. Works like a charm 😉
May I buy you at least a coffee 🦾 
Yes the example is now correct, that's right

**Comment by dushanpantic** [comment]
Haha, that is not necessary, your contributions are more than enough! 🍻

**Pull request merged**
